import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google';
import localFont from "next/font/local";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

// PASTE WEBFLOW CSS IMPORTS HERE IF ANY


const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-plus-jakarta',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Upfront Ops Pipeline Health Calculator",
  description: "Generated by Upfront Ops",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* PASTE WEBFLOW HEAD CONTENT HERE IF ANY */}
      <body
        className={`${plusJakarta.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        {/* PASTE WEBFLOW HEADER HTML HERE */}
        
        <main>
          {/* PASTE WEBFLOW MAIN CONTAINER HTML HERE */}
          {children}
        </main>

        {/* PASTE WEBFLOW FOOTER HTML HERE */}
        <SpeedInsights />
      </body>
    </html>
  );
}