import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google';
import localFont from "next/font/local";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { useEffect } from 'react';
import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-plus-jakarta',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Upfront Ops Pipeline Health Calculator",
  description: "Generated by Upfront Ops",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    function sendHeight() {
      const height = document.documentElement.scrollHeight;
      window.parent.postMessage({
        type: 'calculator-resize',
        height: height
      }, '*');
    }

    // Send height when page loads
    sendHeight();
    
    // Send height again after a short delay to catch any dynamic content
    setTimeout(sendHeight, 1000);

    // Watch for size changes
    const observer = new ResizeObserver(() => {
      sendHeight();
    });

    observer.observe(document.body);

    return () => observer.disconnect();
  }, []);

  return (
    <html lang="en">
      <body
        className={`${plusJakarta.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <main>
          {children}
        </main>
        <SpeedInsights />
      </body>
    </html>
  );
}